export const LOAD_SONGS = 'LOAD_SONGS'
export const LOAD_ARTIST = 'LOAD_ARTIST'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
